### PR TITLE
Add a total page label and support complex URL

### PR DESCRIPTION
**Pull request by cgwxyz**
I added 2 features:

 - add a Total page label,.
 - add support for complex URL.

Some notes:

Current version doesn't support complex URL,such as:"http://github.com/page.php?a=1&page=2&b=3",it will omit all the other GET parameters except "page" which pre- defined. In my working scenario,we usually have long URl with more GET parameters,so I change the source,make it compatiable.

There are some new options:

 - pageParam:the parameter name displayed in URL.
 - lang:merge all the language label into one object,make it more clear.
 - showTotal: Show the total page label.Deault is true.

and some options removed:
 - href
 - hrefVariable

### CODE REVIEW

**Comment by esimakin** [comment]
Hi, lostpaul.

I started code review

**Comment by cgwxyz** [comment]
ok. Any questions let me know.

**Comment by esimakin** [comment]
screenshot
Why do we need the total pages here (red highlight)?
It is not compatible with Bootstrap styles (see http://getbootstrap.com/components/#pagination)

**Comment by cgwxyz** [comment]
Yes,it's really not compatible with Bootstrap styles.
I made this just because it's out of my control during jumping even I could jump to last and then back to first. I hope I could handle the whole thing including total pages.

**Comment by esimakin** [comment]
I suggest a popup on _Last_ button.
What about tooltip?

**Comment by cgwxyz** [comment]
Tooltip is not obvious  but acceptable. Should I launch a new pull request?

**Pull request closed without merging**
