### PR TITLE
Feature/fix jquery 1.7

### PR DESCRIPTION
**Pull request by AngeIII**
when we appending collection of elements like $().add it is not working correctly in jquery 1.9.1, so better to append just an array of elements. 

But appending array of elements doesn't work in jquery 1.7 need to make loop and append.

### CODE REVIEW

**Comment by AngeIII** [comment]
@esimakin , confirm if you review, but don't manually merge into master: with git -flow it is better to create branch /release/ make all changes, merge feature and push new release&tag.

**Comment by esimakin** [comment]
@AngeIII, maybe just use common solution for all jQuery version starts with 1.7
If works for all versions:
```javascript
                var items = this.buildListItems(pages);
                jQuery.each(items, function(key, item){
                    _this.$listContainer.append(item);
                });
```

**Comment by AngeIII** [comment]
I agree,always check for jquery version is ridiculous.

**Comment by AngeIII** [comment]
@esimakin  so I can merge ok? what about 2nd pull request?

**Comment by esimakin** [comment]
TODO: find guidelines for contribution (based on `git rebase`)

**Comment by esimakin** [comment]
Pull request has been merged to `develop` branch

**Pull request closed without merging**
