### PR TITLE
Feature/show total pages #23

### PR DESCRIPTION
**Pull request by AngeIII**
~~Checked jquery, minimal workable 1.8.1~~[see my comment in] #55 
Implemented #23.

Not any text can be used with variables {{page}}, or {{total_pages}}

So for feature #23 only needed last: '[{{total_pages}}]'

### CODE REVIEW

**Comment by AngeIII** [comment]
@esimakin, Done #23.

Also checked jquery. Really minimal workable is 1.8.1

**Comment by AngeIII** [comment]
@esimakin , once you will review I can merge & tag & release.

**Comment by AngeIII** [comment]
Also side note that hrefVarible is no longer supported. (it moved/changed to pageVariable.- and default {{number}} changed to {{page}}

**Comment by esimakin** [comment]
I need to preview (how it looks like on live) the total pages.
Can you create branch for it? (based on `gh-pages` branch)

**Comment by AngeIII** [comment]
@esimakin , done. branch gh-pages-example-show-total-pages

**Comment by AngeIII** [comment]
Also I have idea for {{next_page}}, {{prev_page}} variables. But this can be done separately.

**Comment by esimakin** [comment]
At my opinion there exist two approach (from point UI view):
First -
screenshot from 2015-11-07 21-09-44
Second -
screenshot from 2015-11-07 21-11-43

This plugin supports first approach.

Are you sure that we do this improvement? It is necessary to support hybrid view?

screenshot from 2015-11-07 21-00-54

**Comment by esimakin** [comment]
TODO: make page number customizable through javascript function. For e.g.
```javascript
pageText: function(pageNumber, pageText) {
   ...
    return newPageText; 
}
```

**Comment by AngeIII** [comment]
@esimakin , I think supporting hybrid view is not bad, it is requested in #23 .  Also you can only modify last: '[{{total_pages}}]' and user will se:
first prev 1 2 3 4 5 next [10]
this functionality is requested so I just implemented.

p.s. as about function for text this can help to introduce second approach that you write.

**Comment by smartcorestudio** [comment]
Second or hybrid approach is better, it's more informative because users can see total number of pages

**Comment by esimakin** [comment]
Ok, it may look like
screenshot from 2015-11-07 22-09-48

I'll merge it to develop branch

**Comment by esimakin** [comment]
Pull request has been merged into develop

**Pull request closed without merging**
