### PR TITLE
add a class to the anchor

### PR DESCRIPTION
**Pull request by pogione**

### CODE REVIEW

**Comment by AngeIII** [comment]
You double the url. Need to remove previous code.

**Comment by pogione** [comment]
oops!!

**Comment by AngeIII** [comment]
@esimakin Can be merged into dev.

**Comment by esimakin** [comment]
Hello!
Also you double the `disabledClass` in options.

Please, squash commits into one because commit with message 'Update some_file.js' or 'Fix for another fix' is not looks good.

Don't forget to update min.js file.

**Comment by AngeIII** [comment]
@esimakin is squashing available via UI? https://github.com/blog/2141-squash-your-commits

**Comment by esimakin** [comment]
@AngeIII, yes. It's available

**Comment by esimakin** [comment]
Merged into develop

**Pull request closed without merging**
